Repository arduino/arduino-lint-action, pull requests merged in 2024-10, with the labels that each got.

#350 Upgrade to Node.js 20.x
  .github/CONTRIBUTING.md
  .github/workflows/check-npm.yml
  .github/workflows/check-packaging-ncc-typescript-npm.yml
  .github/workflows/test.yml
  action.yml
Labels: type: imperfection, topic: infrastructure

#413 Use `engines.node` as source of version data for "actions/setup-node" action
  .github/CONTRIBUTING.md
  .github/workflows/check-npm.yml
  .github/workflows/check-packaging-ncc-typescript-npm.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#415 Bump `@types/node` to 20.x
  package-lock.json
  package.json
Labels: type: imperfection, topic: infrastructure

#416 Configure npm to enforce standard project Node.js version
  .github/workflows/check-npm.yml
  .github/workflows/check-packaging-ncc-typescript-npm.yml
  .npmrc
Labels: type: enhancement, topic: infrastructure

#417 Migrate project infrastructure to Task
  .github/CONTRIBUTING.md
  .github/workflows/check-npm-task.yml
  .github/workflows/check-npm.yml
  .github/workflows/check-packaging-ncc-typescript-npm.yml
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/check-toc-task.yml
  .github/workflows/check-toc.yml
  .github/workflows/check-tsconfig-task.yml
  .github/workflows/check-tsconfig.yml
  .github/workflows/spell-check-task.yml
  .github/workflows/spell-check.yml
  .github/workflows/sync-labels-npm.yml
  .github/workflows/test-javascript-jest-task.yml
  .github/workflows/test.yml
  .prettierignore
  README.md
  Taskfile.yml
  jest.config.js
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tsconfig.json
Labels: type: enhancement, topic: infrastructure

#420 Add infrastructure to check for unapproved npm dependency licenses
  .github/CONTRIBUTING.md
  .github/workflows/check-npm-dependencies-task.yml
  .licensed.yml
  .licenses/npm/@actions/core.dep.yml
  .licenses/npm/@actions/exec.dep.yml
  .licenses/npm/@actions/http-client.dep.yml
  .licenses/npm/@actions/io.dep.yml
  .licenses/npm/@actions/tool-cache.dep.yml
  .licenses/npm/@fastify/busboy.dep.yml
  .licenses/npm/semver-6.3.0.dep.yml
  .licenses/npm/semver-7.6.3.dep.yml
  .licenses/npm/tunnel.dep.yml
  .licenses/npm/undici.dep.yml
  .licenses/npm/uuid.dep.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#421 Update snippets in readme to use v2 ref
  README.md
Labels: topic: documentation, type: enhancement
